### ISSUE TITLE
custom theme config in site’s primary configuration file not working

### ISSUE THREAD

**Issue by snowman** [jysperm/hexo-theme-simpleblock#14]
https://hexo.io/docs/configuration.html#Alternate-Theme-Config

```yaml
# FILE: my-blog/_config.yml

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: simpleblock
theme_config:
  banners:
    jade: a(#) this is a banner
```

```yaml
# FILE: my-blog/themes/simpleblock/_config.yml

## Banners && Widgets
banners:
  jade: a(#) 与精子同款的博客主题 simpleblock 现已发布！
```
